### ISSUE TITLE
Join text

### ISSUE THREAD

**Issue by iib0011** [iib0011/omni-tools#2]
Create a page like https://onlinetexttools.com/join-text

**Comment by iib0011** [comment]
@Made4Uo Will you work on this issue?

**Comment by Made4Uo** [comment]
Hi @iib0011 

Yes. Give me a few

**Comment by Made4Uo** [comment]
@iib0011 My bad, I forgot to create a branch and push my changes to the main. 
 
 I have a issue. I cannot figure out why the result text shows a space in every line. I will try to fix this tomorrow. Btw, the checkbox options does not work as expected in the website tps://onlinetexttools.com/join-text

**Comment by iib0011** [comment]
No problem. For next time. I refactored and fixed the `mergeText` function. Thank you

**Comment by iib0011** [comment]
@Made4Uo Please create another branch from main. I made some changes

**Comment by iib0011** [comment]
@Made4Uo forgot to say your changes have been merged to main
