### ISSUE TITLE
Convert jpg to png

### ISSUE THREAD

**Issue by iib0011** [iib0011/omni-tools#4]
Create a page like https://onlinepngtools.com/convert-jpg-to-png

**Comment by omertairi04** [comment]
Where should i put the backend, which is mostly what i will work in?

**Comment by iib0011** [comment]
No we'll do everything in the front

**Comment by omertairi04** [comment]
Oh... the issue is that i have no experience in front end. I will try to do some stuff using online documentation i can find but still cant promise good results.

**Comment by iib0011** [comment]
Ok. Take your time

**Comment by iib0011** [comment]
@hhourani27 Will you work on this issue?

**Comment by hhourani27** [comment]
@iib0011, sorry for the late reply. I'm on it!

**Comment by hhourani27** [comment]
Just finished committing on the branch. I did not do the "PNG Transparency Mask" feature. Do you think it's useful?
If you don't think so, I'll shoot the PR right away

**Comment by iib0011** [comment]
Nice, I think it is useful. Try to make a function which can be used by other tools. Because the PNG mask is used by many other tools.

**Comment by iib0011** [comment]
@hhourani27 Not worth it. Thanks. I didn't find other tools using it

**Comment by hhourani27** [comment]
Ok great! I'll try adding some e2e tests (the image tools are lacking tests), and maybe externalize some color functions (eg. similarity calculations), and then I'll create the PR
